"""Generate native color resources from the shared design source."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[3]
tokens = json.loads((root / 'design/tokens/tokens.json').read_text())
output = root / 'apps/android/app/src/main/res/values/design_colors.xml'
output.write_text('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/generate-tokens.py; edit design/tokens/tokens.json. -->\n<resources>\n' + ''.join(f'    <color name="design_{key}">{value}</color>\n' for key, value in tokens['color'].items() if key != 'scrim') + '</resources>\n')
